# this file has been autogenerated

# git clone https://github.com/pjones/plasma-manager
# cd plasma-manager
# nix run

# EDIT script/rc2nix.rb before running
/*
    "bluedevilglobalrc",
    "breezerc",
    "kaccessrc",
    "kactivitymanagerd-pluginsrc",
    "kalendarrc",
    "kcmshell5rc",
    "kcookiejarrc",
    "kdeconnect.apprc",
    "kded_device_automounterrc",
    "kdialogrc",
    "kmagrc",
    "kmenueditrc",
    "konsolerc",
    "ktrashrc",
    "kwalletmanager5rc",
    "kwin_dialogsrc",
    "kwrited.notifyrc",
    "pavucontrol.ini",
    "plasmaparc",
    "plasma-welcomerc",
    "plasma_calendar_astronomicalevents",
    "powerdevilrc",
    "powermanagementprofilesrc",
    "spectaclerc",
    "startkderc",
    "systemmonitorrc",
    "xdg-desktop-portal-kderc",
 */

{
  programs.plasma = {
    enable = true;
    configFile = {
      "bluedevilglobalrc"."Devices"."connectedDevices" = "";
      "bluedevilglobalrc"."Global"."bluetoothBlocked" = true;
      "breezerc"."Windeco"."DrawBorderOnMaximizedWindows" = true;
      "breezerc"."Windeco"."DrawSizeGrip" = true;
      "kaccessrc"."Mouse"."MouseKeys" = true;
      "kaccessrc"."ScreenReader"."Enabled" = false;
      "kactivitymanagerd-pluginsrc"."Plugin-org.kde.ActivityManager.Resources.Scoring"."keep-history-for" = 12;
      "kalendarrc"."General"."lastOpenedView" = "WeekView";
      "kcmshell5rc"."KFileDialog Settings"."detailViewIconSize" = 16;
      "kcookiejarrc"."Cookie Policy"."Cookies" = false;
      "kdeconnect.apprc"."KFileDialog Settings"."detailViewIconSize" = 0;
      "kded_device_automounterrc"."General"."AutomountOnLogin" = false;
      "kded_device_automounterrc"."General"."AutomountOnPlugin" = false;
      "kdialogrc"."KFileDialog Settings"."detailViewIconSize" = 16;
      "kmagrc"."General Options"."ColorIndex" = 0;
      "kmagrc"."General Options"."FPSIndex" = 2;
      "kmagrc"."General Options"."Geometry" = "460,390";
      "kmagrc"."General Options"."Mode" = "followmouse";
      "kmagrc"."General Options"."RotationIndex" = 0;
      "kmagrc"."General Options"."SelRect" = "1,1,230,158";
      "kmagrc"."General Options"."ShowMouse" = 2;
      "kmagrc"."General Options"."StaysOnTop" = true;
      "kmagrc"."General Options"."ZoomIndex" = 4;
      "kmenueditrc"."General"."SplitterSizes" = "445,544";
      "kmenueditrc"."KFileDialog Settings"."detailViewIconSize" = 16;
      "konsolerc"."Desktop Entry"."DefaultProfile" = "Breath2.profile";
      "konsolerc"."Favorite Profiles"."Favorites" = "Breath2.profile";
      "konsolerc"."General"."ConfigVersion" = 1;
      "konsolerc"."KFileDialog Settings"."detailViewIconSize" = 16;
      "konsolerc"."KonsoleWindow"."FocusFollowsMouse" = true;
      "konsolerc"."KonsoleWindow"."RememberWindowSize" = false;
      "konsolerc"."KonsoleWindow"."ShowWindowTitleOnTitleBar" = true;
      "konsolerc"."PrintOptions"."PrinterFriendly" = true;
      "konsolerc"."PrintOptions"."ScaleOutput" = true;
      "konsolerc"."TabBar"."CloseTabOnMiddleMouseButton" = true;
      "konsolerc"."TabBar"."ExpandTabWidth" = true;
      "ktrashrc"."/home/keks/.local/share/Trash"."Days" = 30;
      "ktrashrc"."/home/keks/.local/share/Trash"."LimitReachedAction" = 1;
      "ktrashrc"."/home/keks/.local/share/Trash"."Percent" = 3;
      "ktrashrc"."/home/keks/.local/share/Trash"."UseSizeLimit" = true;
      "ktrashrc"."/home/keks/.local/share/Trash"."UseTimeLimit" = true;
      "kwalletmanager5rc"."WalletEditor"."AlwaysShowContents" = false;
      "kwalletmanager5rc"."WalletEditor"."SplitterSize" = "49,49";
      "kwin_dialogsrc"."Notification Messages"."altf3warning" = false;
      "kwrited.notifyrc"."Event/NewMessage"."Action" = "Sound|Popup|Taskbar";
      "kwrited.notifyrc"."Event/NewMessage"."Execute" = "";
      "kwrited.notifyrc"."Event/NewMessage"."Logfile" = "";
      "kwrited.notifyrc"."Event/NewMessage"."TTS" = "";
      "pavucontrol.ini"."window"."height" = 774;
      "pavucontrol.ini"."window"."showVolumeMeters" = 1;
      "pavucontrol.ini"."window"."sinkInputType" = 1;
      "pavucontrol.ini"."window"."sinkType" = 0;
      "pavucontrol.ini"."window"."sourceOutputType" = 1;
      "pavucontrol.ini"."window"."sourceType" = 1;
      "pavucontrol.ini"."window"."width" = 1018;
      "plasma-welcomerc"."General"."ShouldShow" = false;
      "plasma_calendar_astronomicalevents"."General"."showLunarPhase" = true;
      "plasma_calendar_astronomicalevents"."General"."showSeason" = true;
      "plasmaparc"."General"."RaiseMaximumVolume" = true;
      "powerdevilrc"."BatteryManagement"."BatteryCriticalAction" = 0;
      "powerdevilrc"."BatteryManagement"."BatteryCriticalLevel" = 10;
      "powerdevilrc"."BatteryManagement"."BatteryLowLevel" = 20;
      "powermanagementprofilesrc"."AC"."icon" = "battery-charging";
      "powermanagementprofilesrc"."AC.DPMSControl"."idleTime" = 1920;
      "powermanagementprofilesrc"."AC.DimDisplay"."idleTime" = 600000;
      "powermanagementprofilesrc"."AC.HandleButtonEvents"."lidAction" = 32;
      "powermanagementprofilesrc"."AC.HandleButtonEvents"."powerButtonAction" = 1;
      "powermanagementprofilesrc"."AC.HandleButtonEvents"."triggerLidActionWhenExternalMonitorPresent" = true;
      "powermanagementprofilesrc"."AC.SuspendSession"."idleTime" = 2520000;
      "powermanagementprofilesrc"."AC.SuspendSession"."suspendThenHibernate" = false;
      "powermanagementprofilesrc"."AC.SuspendSession"."suspendType" = 1;
      "powermanagementprofilesrc"."Battery"."icon" = "battery-060";
      "powermanagementprofilesrc"."Battery.DPMSControl"."idleTime" = 300;
      "powermanagementprofilesrc"."Battery.DimDisplay"."idleTime" = 180000;
      "powermanagementprofilesrc"."Battery.HandleButtonEvents"."lidAction" = 1;
      "powermanagementprofilesrc"."Battery.HandleButtonEvents"."powerButtonAction" = 1;
      "powermanagementprofilesrc"."Battery.HandleButtonEvents"."triggerLidActionWhenExternalMonitorPresent" = true;
      "powermanagementprofilesrc"."Battery.SuspendSession"."idleTime" = 780000;
      "powermanagementprofilesrc"."Battery.SuspendSession"."suspendThenHibernate" = false;
      "powermanagementprofilesrc"."Battery.SuspendSession"."suspendType" = 1;
      "powermanagementprofilesrc"."Battery.WirelessPowerSaving"."btOption" = 0;
      "powermanagementprofilesrc"."Battery.WirelessPowerSaving"."wifiOption" = 0;
      "powermanagementprofilesrc"."Battery.WirelessPowerSaving"."wwanOption" = 0;
      "powermanagementprofilesrc"."LowBattery"."icon" = "battery-low";
      "powermanagementprofilesrc"."LowBattery.BrightnessControl"."value" = 10;
      "powermanagementprofilesrc"."LowBattery.DPMSControl"."idleTime" = 60;
      "powermanagementprofilesrc"."LowBattery.DimDisplay"."idleTime" = 60000;
      "powermanagementprofilesrc"."LowBattery.HandleButtonEvents"."lidAction" = 8;
      "powermanagementprofilesrc"."LowBattery.HandleButtonEvents"."powerButtonAction" = 8;
      "powermanagementprofilesrc"."LowBattery.HandleButtonEvents"."triggerLidActionWhenExternalMonitorPresent" = true;
      "powermanagementprofilesrc"."LowBattery.SuspendSession"."idleTime" = 120000;
      "powermanagementprofilesrc"."LowBattery.SuspendSession"."suspendThenHibernate" = false;
      "powermanagementprofilesrc"."LowBattery.SuspendSession"."suspendType" = 8;
      "powermanagementprofilesrc"."LowBattery.WirelessPowerSaving"."btOption" = 1;
      "powermanagementprofilesrc"."LowBattery.WirelessPowerSaving"."wifiOption" = 1;
      "powermanagementprofilesrc"."LowBattery.WirelessPowerSaving"."wwanOption" = 1;
      "powermanagementprofilesrc"."migration"."kdedShortcutMigration" = true;
      "spectaclerc"."Annotations"."annotationToolType" = 7;
      "spectaclerc"."General"."autoSaveImage" = true;
      "spectaclerc"."General"."clipboardGroup" = "PostScreenshotCopyImage";
      "spectaclerc"."General"."onLaunchAction" = "DoNotTakeScreenshot";
      "spectaclerc"."General"."printKeyActionRunning" = "StartNewInstance";
      "spectaclerc"."General"."rememberLastRectangularRegion" = "Always";
      "spectaclerc"."General"."showMagnifier" = true;
      "spectaclerc"."GuiConfig"."captureDelay" = 2;
      "spectaclerc"."KFileDialog Settings"."detailViewIconSize" = 16;
      "spectaclerc"."Save"."compressionQuality" = 75;
      "spectaclerc"."Save"."defaultSaveLocation" = "file:///home/keks/Pictures/Screenshots";
      "spectaclerc"."Save"."lastUsedSaveMode" = "Save";
      "startkderc"."General"."systemdBoot" = true;
      "systemmonitorrc"."General"."height" = 952;
      "systemmonitorrc"."General"."lastVisitedPage" = "overview.page";
      "systemmonitorrc"."General"."pageOrder" = "overview.page,applications.page,history.page,processes.page,new_page.page";
      "systemmonitorrc"."General"."width" = 1232;
      "systemmonitorrc"."TaskDialog"."ioInformation" = 5;
      "systemmonitorrc"."TaskDialog"."ioUnits" = 1;
      "systemmonitorrc"."TaskDialog"."normalizeCPUUsage" = true;
      "systemmonitorrc"."TaskDialog"."showCommandLineOptions" = false;
      "systemmonitorrc"."TaskDialog"."showTooltips" = true;
      "systemmonitorrc"."TaskDialog"."showTotals" = true;
      "systemmonitorrc"."TaskDialog"."units" = 1;
      "systemmonitorrc"."TaskDialog"."updateIntervalMSecs" = 2000;
      "systemmonitorrc"."TaskDialog"."version" = 10;
      "xdg-desktop-portal-kderc"."KFileDialog Settings"."detailViewIconSize" = 16;
      "xdg-desktop-portal-kderc"."KFileDialog Settings"."iconViewIconSize" = 64;
      "xdg-desktop-portal-kderc"."KFileDialog Settings"."listViewIconSize" = 64;
    };
  };
}
