# file: hardware/filesystem-laptop.nix
# desc: (mostly) auto generated file for the hardware of my laptop

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs
, ssd-mnt, ssd-name
, hdd-mnt, hdd-name
, nvm-mnt, nvm-name
, ... }:

let
  ssd-label   = "/dev/disk/by-label/${ssd-name}";
  ssd-keyfile = "/dev/disk/by-partuuid/c58965ae-8061-714c-94ef-11c57da14a63";

  hdd-label   = "/dev/disk/by-label/${hdd-name}";
  hdd-keyfile = "/dev/disk/by-partuuid/3375b91e-8e21-7e46-ad42-fcdc11b8858a";

  nvm-label   = "/dev/disk/by-label/${nvm-name}";
  nvm-keyfile = "/dev/disk/by-partuuid/7bf59cfb-f4ea-c047-84b0-8b7ac74d76a4";
in
{
  /*
   * fTPM not working under Linux
   * TEMPORARY SOLUTION (throwing away single drives without thinking should work and I can still use Wake on LAN)
   * find -L /dev/disk -samefile /dev/sdh2
   * dd status=progress bs=2048 if=/etc/nixos/secrets/keys/luks/main of=/dev/sdh2 seek=0
   */
  boot.initrd.luks.devices = {
    "main1" = {
      device = "${ssd-label}1";
      keyFile = ssd-keyfile;
      keyFileSize = 2048;
    };
    "main2" = {
      device = "${ssd-label}2";
      keyFile = ssd-keyfile;
      keyFileSize = 2048;
    };
  };

  # https://www.freedesktop.org/software/systemd/man/latest/crypttab.html
  # nofail -> no Before=cryptsetup.target
  environment.etc."crypttab".text = ''
    ${hdd-name}1  ${hdd-label}1   ${hdd-keyfile}  nofail,keyfile-size=2048
    ${hdd-name}3  ${hdd-label}3   ${hdd-keyfile}  nofail,keyfile-size=2048
    ${hdd-name}4  ${hdd-label}4   ${hdd-keyfile}  nofail,keyfile-size=2048

    ${nvm-name}1  ${nvm-label}1   ${nvm-keyfile}  nofail,keyfile-size=2048,discard
    ${nvm-name}3  ${nvm-label}3   ${nvm-keyfile}  nofail,keyfile-size=2048,discard
    ${nvm-name}4  ${nvm-label}4   ${nvm-keyfile}  nofail,keyfile-size=2048,discard
    ${nvm-name}5  ${nvm-label}5   ${nvm-keyfile}  nofail,keyfile-size=2048,discard
  '';

  # https://www.freedesktop.org/software/systemd/man/latest/systemd-fstab-generator.html
  fileSystems =
  let
    bfs-opts = [ "compress=zstd:3" ];
  in
  {
    "/boot" = {
      device = "/dev/disk/by-uuid/F6A6-57AC";
      fsType = "vfat";
      options = [
        "umask=0077"
        "shortname=winnt"
      ];
    };
    "/nix" = {
      device = ssd-label;
      fsType = "btrfs";
      options = bfs-opts ++ [ "subvol=nix" ];
      # implicit neededForBoot
    };

    "${ssd-mnt}" = {
      device = ssd-label;
      fsType = "btrfs";
      options = bfs-opts ++ [ "subvol=/" ];
      neededForBoot = true;
    };
    "${hdd-mnt}" = {
      device = hdd-label;
      fsType = "btrfs";
      options = [
        "compress-force=zstd:3"
        "subvol=/"
        "nofail" # no Before=local-fs.target
        "x-systemd.requires=systemd-cryptsetup@${hdd-name}1.service"
        "x-systemd.requires=systemd-cryptsetup@${hdd-name}3.service"
        "x-systemd.requires=systemd-cryptsetup@${hdd-name}4.service"
      ];
    };
    "${nvm-mnt}" = {
      device = nvm-label;
      fsType = "btrfs";
      options = bfs-opts ++ [
        "subvol=/"
        "nofail" # no Before=local-fs.target
        "x-systemd.requires=systemd-cryptsetup@${nvm-name}1.service"
        "x-systemd.requires=systemd-cryptsetup@${nvm-name}3.service"
        "x-systemd.requires=systemd-cryptsetup@${nvm-name}4.service"
        "x-systemd.requires=systemd-cryptsetup@${nvm-name}5.service"
      ];
    };

    "/mnt/backup/USB/data" = {
      device = "/dev/mapper/usb-backup";
      fsType = "btrfs";
      options = [ "noauto" ];
    };
  };

  swapDevices = [
    {
      # random encryption will resetup the LUKS header
      # using by-partuuid should not change between system reboots or kernel updates
      device = "/dev/disk/by-partuuid/85439545-b3f4-f742-948f-e3a7190f5fc7";
      randomEncryption.enable = true;
      options = [ "nofail" ];
    }
  ];
}
