#!/bin/bash

set -e

[ -n "${MY_IFLINK}" ] || exit 0
[ -n "${MY_IPV6_ULU}" ] || exit 0

IFLINK="$1"
NMMODE="$2"

set-ipv6-ulu() {
	if ip addr show "${IFLINK}" | grep -q "${MY_IPV6_ULU}"; then
		exit 0
	fi

	# https://de.wikipedia.org/wiki/IPv6#Unique_Local_Unicast
	ip addr add "${MY_IPV6_ULU}" dev "${IFLINK}"
}

case "${IFLINK}" in
"${MY_IFLINK}")
	case "${NMMODE}" in
	up)
		set-ipv6-ulu
	;;
	esac
;;
esac

exit 0
