#!/bin/bash

set -e

[ -n "${MY_IFLINK}" ] || exit 0
[ -n "${MY_IPV6_ULU}" ] || exit 0

IFLINK="$1"
NMMODE="$2"

case "${IFLINK}" in
"${MY_IFLINK}")
	case "${NMMODE}" in
	up)
		# https://de.wikipedia.org/wiki/IPv6#Unique_Local_Unicast
		ip addr add "${MY_IPV6_ULU}" dev "${IFLINK}"
	;;
	esac
;;
esac

exit 0
