#!/bin/bash

set -e

IFLINK="$1"
NMMODE="$2"


ddns_stop() {
	systemctl stop podman-ddns-v4.service
	systemctl stop podman-ddns-v6.service
}
ddns_start() {
	systemctl start podman-ddns-v4.service
	systemctl start podman-ddns-v6.service
}


case "${NMMODE}" in
"vpn-up")
	echo "ddns_stop: vpn=${IFLINK} went up"
	ddns_stop
;;
"vpn-down")
	echo "ddns_start: vpn=${IFLINK} went down"
	ddns_start
;;
esac

exit 0
