{ config, pkgs, data-dir, ...}:

{
  imports = [ ../system/server-and-config-update.nix ];

  systemd = {
    services."server-and-config-update@DownloadBackup" = {
      # fixes empty unit file (extends template unit)
      overrideStrategy = "asDropin";
      # overrides.conf (generated by Nix) resets PATH variable
      path = [
        pkgs.gnutar
        pkgs.gzip
        pkgs.openssh
        pkgs.rsync
      ];
      # extra changes
      description = "Generates Backups from different Remote Systems";
      serviceConfig = {
        ProtectHome = "read-only";
        BindReadOnlyPaths = [
          "/etc/ssh/ssh_config"
        ];
        ReadWritePaths = "${data-dir}/Documents/BackUp";
      };
    };
    timers."server-and-config-update@DownloadBackup" = {
      # only for systemd unit masking
      enable = true;
      # fixes empty unit file (extends template unit)
      overrideStrategy = "asDropin";
      # this auto enables this unit in the system context
      wantedBy = [ "timers.target" ];
      # custom time
      timerConfig = {
        OnCalendar = "Wed *-*-* 20:40:00";
        RandomizedDelaySec = "5min";
      };
    };
  };

  /*
   * manual preparation steps:
   *   sudo -i
   *
   *   mkdir -p ~/.secrets/ssh
   *   ssh-keygen
   *   ln -srv ~/.secrets/ssh/id_ed25519 ~/.secrets/ssh/id_rsa_hetzner
   *   ln -srv ~/.secrets/ssh/id_ed25519 ~/.secrets/ssh/id_rsa_pihole
   *
   *   mkdir -p ~/.config/ssh
   *   ssh hetzner-mailcow
   *   ssh pihole-root
   */
}


