# file: hardware/filesystem-laptop.nix
# desc: (mostly) auto generated file for the hardware of my laptop

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot = {
    initrd = {
      # Setup keyfile
      secrets = {
        "/crypto_keyfile.bin" = null;
      };

      luks.devices = {
        "luks-c720b152-baf0-4336-bb04-83f01857cfab" = {
          device = "/dev/disk/by-uuid/c720b152-baf0-4336-bb04-83f01857cfab";
        };

        # Enable swap on luks
        "luks-499f4ab6-e61f-42f0-8665-6115d67a5222" = {
          device = "/dev/disk/by-uuid/499f4ab6-e61f-42f0-8665-6115d67a5222";
          keyFile = "/crypto_keyfile.bin";
        };
      };
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/30b952c5-8a77-440a-a7e7-d3a9164c6f31";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/90CE-7A63";
      fsType = "vfat";
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/4562c744-f2c8-4358-812d-446a35fc1efe"; }
  ];
}
