# file: hardware/filesystem-laptop.nix
# desc: (mostly) auto generated file for the hardware of my laptop

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot = {
    initrd = {
      # Setup keyfile
      /*
      secrets = {
        "/crypto_keyfile.bin" = null;
      };
       */

      luks.devices = {
        "root" = {
          device = "/dev/disk/by-uuid/c720b152-baf0-4336-bb04-83f01857cfab";
        };

        # Enable swap on luks
        /*
        "swap" = {
          device = "/dev/disk/by-uuid/499f4ab6-e61f-42f0-8665-6115d67a5222";
          keyFile = "/crypto_keyfile.bin";
        };
         */
      };
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "compress=zstd:3"
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/90CE-7A63";
      fsType = "vfat";
      options = [
        "umask=0077"
        "shortname=winnt"
      ];
    };

    "/home" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=home"
        "compress=zstd:3"
      ];
    };

    "/mnt" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=mnt"
        "compress=zstd:3"
      ];
    };

    "/mnt/array" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=mnt-array"
        "compress=zstd:3"
      ];
    };

    "/mnt/cache" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=/"
        "compress=zstd:3"
      ];
    };

    "/nix" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "compress=zstd:3"
      ];
    };
  };

  /*
  swapDevices = [
    { device = "/dev/mapper/swap"; }
  ];
   */
}
