# file: hardware/filesystem-laptop.nix
# desc: (mostly) auto generated file for the hardware of my laptop

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot = {
    initrd = {
      luks.devices = {
        "root" = {
          device = "/dev/disk/by-uuid/c720b152-baf0-4336-bb04-83f01857cfab";
        };
      };
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "compress=zstd:3"
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/90CE-7A63";
      fsType = "vfat";
      options = [
        "umask=0077"
        "shortname=winnt"
      ];
    };

    "/home" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=home"
        "compress=zstd:3"
      ];
    };

    "/mnt" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=mnt"
        "compress=zstd:3"
      ];
    };

    "/mnt/array" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=mnt-array"
        "compress=zstd:3"
      ];
    };

    "/mnt/cache" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=/"
        "compress=zstd:3"
      ];
    };

    "/nix" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "compress=zstd:3"
      ];
    };
  };

  swapDevices = [
    {
      # random encryption will resetup the LUKS header
      # using by-id should not change between system reboots or kernel updates
      device = "/dev/disk/by-id/nvme-KINGSTON_SNVS500G_50026B76856C0884-part3";
      randomEncryption.enable = true;
    }
  ];
}
